/science_interface/centrifuge_pos_names: ["pos 0",
                                          "pos 1",
                                          "pos 2",
                                          "pos 3",
                                          "pos 4",
                                          "pos 5",
                                          "pos 6",
                                          "pos 7",
                                          "pos 8",
                                          "pos 9",
                                          "pos 10",
                                          "pos 11"]

/science_interface/auger_min: 0
/science_interface/auger_max: 20 # TODO: configure

